"""GDI values used by the emulator, independent of WMF record opcodes."""

PS_SOLID = 0
PS_DASH = 1
PS_DOT = 2
PS_DASHDOT = 3
PS_DASHDOTDOT = 4
PS_NULL = 5
PS_INSIDEFRAME = 6

BS_SOLID = 0
BS_NULL = 1
BS_HATCHED = 2
BS_PATTERN = 3

TRANSPARENT = 1
OPAQUE = 2
ALTERNATE = 1
WINDING = 2

R2_BLACK = 1
R2_NOT = 6
R2_NOP = 11
R2_COPYPEN = 13
R2_WHITE = 16

MM_TEXT = 1
MM_LOMETRIC = 2
MM_HIMETRIC = 3
MM_LOENGLISH = 4
MM_HIENGLISH = 5
MM_TWIPS = 6
MM_ISOTROPIC = 7
MM_ANISOTROPIC = 8

TA_UPDATECP = 1
TA_RTLREADING = 0x100
ETO_OPAQUE = 2
ETO_CLIPPED = 4
ETO_RTLREADING = 0x80
ETO_NUMERICSLOCAL = 0x400
ETO_NUMERICSLATIN = 0x800

BLACKONWHITE = 1
WHITEONBLACK = 2
COLORONCOLOR = 3
HALFTONE = 4

FLOODFILLBORDER = 0
FLOODFILLSURFACE = 1
